kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: lomero/spark-arq:kubernetes-spark
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args: ["/home/sparker/spark-master"]
          ports:
            - containerPort: 22
            - containerPort: 7077
            - containerPort: 8080
            - containerPort: 9000
            - containerPort: 8088 # Hadoop - Resource UI
            - containerPort: 9870 # Hadoop - NameNode UI
            - containerPort: 9864 # Hadoop - DataNode UI
            - containerPort: 19888 # Hadoop - Job History UI
            - containerPort: 18080
